# ---------- Stage 1: Build TikZiT ----------
FROM ubuntu:22.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git cmake pkg-config wget ca-certificates \
    qmake6 qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-pdf-dev \
    flex bison \
    libx11-xcb1 libxrender1 libxcb1 libxkbcommon-x11-0 \
    libpoppler-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /src
# Copy source into container
COPY . /src

# --- CHANGE 1: Fix compilation error (Qt API mismatch) ---
# Replaces 'pagePointSize' with 'pageSize' in the source code before building
RUN sed -i 's/pagePointSize/pageSize/g' src/data/pdfdocument.cpp

RUN mkdir -p /src/build && cd /src/build && qmake6 ../tikzit.pro && make -j$(nproc)

# Collect built binary and required shared libs into /out
RUN mkdir -p /out/bin /out/lib && \
    cp /src/build/tikzit /out/bin/ || cp /src/build/release/tikzit /out/bin/ || true && \
    ldd /out/bin/tikzit | awk '/=>/ {print $(NF-1)}' | grep '^/' | xargs -I '{}' cp -v '{}' /out/lib || true

# ---------- Stage 2: Runtime ----------
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1
EXPOSE 8080 5901

# minimal runtime deps + VNC/noVNC environment
# minimal runtime deps + VNC/noVNC environment
# --- OPTIMIZATION: SPLIT INTO LAYERS FOR BETTER UPLOADS ---

# Layer 1: The Desktop Environment (XFCE + VNC) ~300MB
RUN apt-get update && apt-get install -y --no-install-recommends \
    xfce4 xfce4-goodies \
    tigervnc-standalone-server tigervnc-common tigervnc-tools \
    websockify novnc supervisor python3 git wget ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Layer 2: The Heavy Qt Libraries (The "Nuclear" Base) ~500MB
# If this layer uploads successfully once, it is cached forever!
RUN apt-get update && apt-get install -y --no-install-recommends \
    qt6-base-dev libqt6pdf6 libpoppler-dev libqt6svg6 \
    libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Layer 3: Fonts, Icons, Doxygen, and XCB Helpers ~150MB
RUN apt-get update && apt-get install -y --no-install-recommends \
    adwaita-icon-theme doxygen graphviz \
    dbus-x11 x11-xserver-utils xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable \
    libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
    libxcb-render-util0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# create a non-root user for the session
RUN useradd -m -s /bin/bash tikzituser

# copy built app (We only copy the binary, relying on installed libs for stability)
COPY --from=builder /out/bin/tikzit /usr/local/bin/tikzit

# --- CHANGE 3: Removed the manual library copy and LD_LIBRARY_PATH ---
# We installed the libraries via apt in Change 2, which solves the "UndefinedVar" warning
# and prevents "Qt platform plugin xcb not found" errors.

# install noVNC (Pinned to v1.4.0 to fix JS errors)
RUN git clone --depth 1 --branch v1.4.0 https://github.com/novnc/noVNC.git /opt/noVNC || true
RUN git clone --depth 1 https://github.com/novnc/websockify.git /opt/noVNC/utils/websockify || true

# copy supervisor config and entrypoint
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# --- CRITICAL: Copy the Doxygen Docs into the image ---
# This takes the 'docs' folder from your laptop (generated by publish_all.sh)
# and puts it inside the image.
COPY docs /src/docs

# Create default index symlink
RUN ln -s /opt/noVNC/vnc.html /opt/noVNC/index.html

VOLUME ["/home/tikzituser/.vnc", "/home/tikzituser/.local/share/tikzit"]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]